### ISSUE TITLE
StylesheetOptions.Parameters is not used

### ISSUE THREAD

**Issue by jbuchbinder** [jbowtie/ratago#12]
`StylesheetOptions.Parameters` is not used within the codebase during stylesheet processing, so passing named parameters seems to be broken.

**Comment by jbowtie** [comment]
You're right about that -- I simply don't have any test cases that require named parameters at the moment.

If anyone wants to contribute one we can look at fixing this.

**Comment by jbuchbinder** [comment]
It's easy enough -- simply define a string and integer parameter, perform a mathematical operation with one and insert the second. Something like this:

```
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
<xsl:param name="number" as="xs:integer" />
<xsl:param name="text" as="xs:string" />

. . .
    <xsl:value-of select="$text"/>
. . .
    <xsl:value-of select="$number + 1"/>
. . .

</xsl:stylesheet>
```

Those should be sufficient, I'd think.
