### ISSUE TITLE
How does StripSpace work

### ISSUE THREAD

**Issue by jbampton** [jbowtie/ratago#22]
Hey @jbowtie this XSLT library looks good.  I have been using it today :)

Can you please show me an example of how StripSpace and indentation works ?

Thanks 👍

**Comment by jbowtie** [comment]
Are you asking how the standard `<xsl:strip-space>` instruction works, or are you asking how it's implemented internally?  You shouldn't need to do anything with it at the API level.

**Comment by jbampton** [comment]
Hey @jbowtie thanks for responding.  Sorry for my slow reply.

I do understand how XSLT works and strip-space.

I have only been learning Golang for about 2.5 months and when I first tried your library I did not get "everything" working.  I think it must have been my mistake.  I will try it again when I get some spare time.

You can close this issue now since you said it works.  Thanks once again 👍
