### ISSUE TITLE
Fatal errors when running

### ISSUE THREAD

**Issue by bobbylight** [jbowtie/ratago#24]
More of a question than a bug.  I'm trying to use this package in a project and get the following error when running `go run *.go`:

```bash
toby:go-xml-to-csv robert$ go run *.go
^[^[# github.com/jbowtie/gokogiri/help
../../go/src/github.com/jbowtie/gokogiri/help/help.go:6:10: fatal error: 'libxml/tree.h' file not found
#include <libxml/tree.h>
         ^~~~~~~~~~~~~~~
1 error generated.
# github.com/jbowtie/gokogiri/xpath
../../go/src/github.com/jbowtie/gokogiri/xpath/expression.go:4:10: fatal error: 'libxml/xpath.h' file not found
#include <libxml/xpath.h>
         ^~~~~~~~~~~~~~~~
1 error generated.
```
Do I need to do some kind of configuration with cgo to get things building/running?  The gokogiri doc says to apt-get libxml2-dev; I've installed libxml2 via brew since I'm on os x (no libxml2-dev package was known to brew).

**Comment by jbowtie** [comment]
I don't do Mac development/testing but a quick internet search turned up this link regarding missing headers:

https://silvae86.github.io/sysadmin/mac/osx/mojave/beta/libxml2/2018/07/05/fixing-missing-headers-for-homebrew-in-mac-osx-mojave/

**Comment by bobbylight** [comment]
Thanks, that did the trick.  I'm new to go and years of Java have rotted my brain.
